version: '3.8'

services:
  database:
    container_name: mysql_db
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: beespace
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    container_name: docker-compose-test
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PROFILES: blue
      ENV: blue
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/beespace?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    env_file:
      - .env
#      - ~/.env
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network: